#!/bin/bash
export GIT_REPO=$HOME/prj/hpssic/dev
export CRAWL_CONF=$GIT_REPO/hpss-dev01.crawl.cfg
export PYTHONPATH=$GIT_REPO
export CRONOUT=/tmp/cronjob.$$.out
export TESTDIR=$GIT_REPO/hpssic/test

/bin/date "+%Y.%m%d %H:%M:%S" >> $CRONOUT
cd $HOME/prj/hpssic/dev
/usr/bin/py.test --cov hpssic --all >> $CRONOUT 2>&1
STATUS=$?
/bin/date "+%Y.%m%d %H:%M:%S" >> $CRONOUT

SUMMARY=$(grep "seconds ===" $CRONOUT | sed -e "s/==*/===/g")

SUBJECT="HPSSIC tests: $SUMMARY"
/bin/mail -s "$SUBJECT" tbarron@ornl.gov tusculum@gmail.com < $CRONOUT
/bin/rm $CRONOUT
