#!/bin/bash
export GIT_REPO=$HOME/prj/hpssic/dev
export CRAWL_CONF=$GIT_REPO/hpss-dev01.crawl.cfg
export PYTHONPATH=$GIT_REPO
export CRONOUT=/tmp/cronjob.$$.out
export TESTDIR=$GIT_REPO/hpssic/test
export YMDHM=`date +"%Y.%m%d.%H%M"`

/bin/date "+%Y.%m%d %H:%M:%S" >> $CRONOUT 2>&1
cd $HOME/prj/hpssic/dev
. $HOME/venv/hpssic/bin/activate
echo "Activating environment hpssic" >> $CRONOUT 2>&1

/usr/bin/py.test --cov hpssic --all >> $CRONOUT 2>&1
/usr/bin/coverage report -m > coverage/$YMDHM

/bin/date "+%Y.%m%d %H:%M:%S" >> $CRONOUT 2>&1

SUMMARY=$(grep "seconds ===" $CRONOUT | sed -e "s/==*/===/g")

SUBJECT="HPSSIC tests: $SUMMARY"
/bin/mail -s "$SUBJECT" tbarron@ornl.gov tusculum@gmail.com < $CRONOUT
/bin/rm $CRONOUT
