#!/usr/bin/env python
#
# An example hook script that is called after a successful
# commit is made.
#
# To enable this hook, rename this file to "post-commit".

os.system("git describe > .hpssic_version")
