#!/usr/bin/env python

from distutils.core import setup

setup(name='hpssic',
      version='2014.0725dev',
      description='HPSS Integrity Crawler',
      author='Tom Barron',
      author_email='tbarron@ornl.gov',
      url='https://github.com/ORNL-TechInt/hpss-crawler',
      scripts=['bin/ztool.py',
               'bin/cv',
               'bin/crawl'],
      py_modules=['Alert',
                  'Checkable',
                  'CrawlConfig',
                  'CrawlDBI',
                  'crawl_lib',
                  'CrawlPlugin',
                  'crawl',
                  'cv',
                  'daemon',
                  'Dimension',
                  'fakesmtp',
                  'hpss',
                  'hsitool',
                  'mpra_lib',
                  'mpra',
                  'pexpect',
                  'rpt_lib',
                  'rpt',
                  'tcc_lib',
                  'tcc',
                  'testhelp',
                  'toolframe',
                  'util'],
      packages=[],
      )
